"""
Columns for PostgreSQL database from SportMonks API
"""

FIXTURE_COLUMNS = ["id", "league_id", "league.name", "visitorTeam.country_id",
                   "league.country.name", "season_id",
                   "venue_id", "venue.name", "referee_id", "referee.fullname",
                   "localTeam.id", "localTeam.name", "visitorTeam.id", "visitorTeam.name",
                   "standings.localteam_position", "standings.visitorteam_position",
                   "localCoach.coach_id", "localCoach.common_name",
                   "visitorCoach.coach_id", "visitorCoach.common_name",
                   "time.starting_at.date_time",
                   "time.starting_at.date", "time.starting_at.time",
                   "time.starting_at.timezone", "formations.localteam_formation",
                   "formations.visitorteam_formation",
                   "scores.localteam_score",
                   "scores.visitorteam_score", "scores.ht_score", "scores.ft_score",
                   "attendance", "weather_report.code",
                   "weather_report.temperature_celcius.temp",
                   "weather_report.clouds", "weather_report.humidity",
                   "weather_report.wind.speed", "weather_report.coordinates.lat",
                   "weather_report.coordinates.lon",
                   "home.shots.total", "home.shots.ongoal", "home.shots.blocked",
                   "home.shots.offgoal", "home.shots.insidebox", "home.shots.outsidebox",
                   "home.passes.total", "home.passes.accurate", "home.passes.percentage",
                   "home.attacks.attacks", "home.attacks.dangerous_attacks", "home.fouls",
                   "home.corners", "home.offsides", "home.possessiontime", "home.yellowcards",
                   "home.redcards", "home.yellowredcards", "home.saves", "home.substitutions",
                   "home.goal_kick", "home.goal_attempts", "home.free_kick",
                   "home.throw_in", "home.penalties", "home.injuries",
                   "away.shots.total", "away.shots.ongoal", "away.shots.blocked",
                   "away.shots.offgoal", "away.shots.insidebox", "away.shots.outsidebox",
                   "away.passes.total", "away.passes.accurate", "away.passes.percentage",
                   "away.attacks.attacks", "away.attacks.dangerous_attacks", "away.fouls",
                   "away.corners", "away.offsides", "away.possessiontime", "away.yellowcards",
                   "away.redcards", "away.yellowredcards", "away.saves", "away.substitutions",
                   "away.goal_kick", "away.goal_attempts", "away.free_kick",
                   "away.throw_in", "away.penalties", "away.injuries"]

RENAME_FIXT_COLUMNS = {"weather_report.temperature_celcius.temp": "temp_celsius",
                       "weather_report.clouds": "clouds", "weather_report.humidity": "humidity",
                       "weather_report.wind.speed": "wind_speed", "weather_report.coordinates.lat": "latitude",
                       "weather_report.coordinates.lon" : "longtitude",
                       "formations.localteam_formation": "home_formation",
                       "formations.visitorteam_formation": "away_formation",
                       "scores.localteam_score": "home_goals", "scores.visitorteam_score": "away_goals",
                       "scores.localteam_pen_score": "home_pen_goals", "scores.visitorteam_pen_score": "away_pen_goals",
                       "scores.ht_score": "HT", "scores.ft_score": "FT", "time.starting_at.date": "date",
                       "time.starting_at.time": "time", "time.starting_at.timezone": "timezone",
                       "standings.localteam_position": "home_standings", "standings.visitorteam_position": "away_standings",
                       "localTeam.id": "home_id", "localTeam.name": "home_name",
                       "visitorTeam.id": "away_id", "visitorTeam.name": "away_name",
                       "league.name": "league", "referee.fullname": "referee",
                       "venue.name": "venue", "localCoach.coach_id": "home_coach_id",
                       "localCoach.common_name": "home_coach", "visitorCoach.coach_id": "away_coach",
                       "visitorCoach.common_name": "away_coach", "home.attacks.attacks": "home.attacks",
                       "away.attacks.attacks": "away.attacks", "visitorTeam.country_id": "country_id",
                       "league.country.name": "country", "time.starting_at.date_time": "datetime"}

LEAGUES = {"EPL": 8, "Championship": 9, "League1": 12, "League2": 14,
           "Eredivise": 72, "Bundesliga": 82, "Tipico_Bundesliga": 181,
           "Pro_League": 208, "First_Divison_B": 211, "Superliga": 271,
           "First_Division": 274, "Ligue1": 301, "SerieA": 384,
           "Eliteserien": 444, "Primeiria_Liga": 462, "Premier_League": 486,
           "Premiership": 501, "La_Liga": 564, "Allsvenskan": 573,
           "Super_Lig": 600}
